minify: true
custom_file_path:
  style: source/_data/styles.styl
  sidebar: source/_data/footer.njk
  footer: source/_data/footer.njk
scheme: Muse
#darkmode: true
avatar: 
  url: https://cdn.jsdelivr.net/gh/tongzhugroup/tongzhugroup.github.io@7cebddef46c046a7a1119199002fe15b1c2dec24/logo.jpg
favicon:
  small: https://cdn.jsdelivr.net/gh/tongzhugroup/tongzhugroup.github.io@7cebddef46c046a7a1119199002fe15b1c2dec24/logo.jpg
  medium: https://cdn.jsdelivr.net/gh/tongzhugroup/tongzhugroup.github.io@7cebddef46c046a7a1119199002fe15b1c2dec24/logo.jpg
  apple_touch_icon: https://cdn.jsdelivr.net/gh/tongzhugroup/tongzhugroup.github.io@7cebddef46c046a7a1119199002fe15b1c2dec24/logo.jpg
  safari_pinned_tab: https://cdn.jsdelivr.net/gh/tongzhugroup/tongzhugroup.github.io@7cebddef46c046a7a1119199002fe15b1c2dec24/logo.jpg
menu:
  HOME: / 
  TEAM: /people/ 
  RESEARCH: /research/
  PUBLICATIONS: /publications/
  SOFTWARES: /softwares/
  TEACHING: /teaching/
  MEMORY: /memory/
  "GROUP SEMINAR": /group-seminar/
  TIPS: /tips/
sidebar:
  position: right
  display: hide
site_state: false
toc:
  enable: false
preconnect: true
exturl: true
mediumzoom: true
lazyload: true
pangu: false
vendors:
  internal: jsdelivr
  plugins: jsdelivr
font:
  enable: true
  global:
    family: Open Sans
    size: 0.6875
  title:
    size: 1.625
footer:
  powered: false
index_with_subtitle: true
motion:
  enable: false
math:
  every_page: false
  mathjax:
    enable: true
